---
- name: Deploy vlan
  hosts: leafs
  connection: local
  gather_facts: no

  tasks:
      - name: obtaining login credentials
        include_vars: credentials.yml

      - name: obtaining vlan list
        include_vars: vlan_list.yml

      - name: obtaining server port list
        include_vars: port_list.yml

      - name: configuring vlans listed in the vlan_list.yml
        nxos_vlan: vlan_id="{{ item.id }}"  name="{{ item.name }}" state="{{ item.state }}" provider="{{ creds }}"
        with_items: "{{ vlan_list }}"

      - name: configuring description on switch ports based on the information in port_list.yml file
        nxos_interface: interface="{{ item.port }}" description="{{ item.description }}" provider="{{ creds }}"
        with_items: "{{ port_list }}"

      - name: configuring server ports based on the information in port_list.yml file
        nxos_switchport: interface="{{ item.port }}" mode=access access_vlan="{{ item.vlan }}" provider="{{ creds }}"
        with_items: "{{ port_list }}"

      - name: Saving Configuration
        nxos_config:
          provider: "{{ creds }}"
          lines:
            - 'copy run start'
