---
- name: Deploy single vlan
  hosts: leafs
  connection: local
  gather_facts: no

  tasks:
      - name: obtaining login credentials
        include_vars: credentials.yml

      - name: configuring vlan
        nxos_vlan: vlan_id=10  name=example-1  state=present provider="{{ creds }}"

      - name: Saving Configuration
        nxos_config:
          save: yes
          provider: "{{ creds }}"
