---
- name: Deploy vlan
  hosts: all
  connection: local
  gather_facts: no

  tasks:
      - name: obtaining login credentials
        include_vars: credentials.yml

      - name: obtaining  vlan list
        include_vars: vlan_list.yml

      - name: configuring vlans using vlan_list.yml
        nxos_vlan: vlan_id="{{ item.id }}"  name="{{ item.name }}" state="{{ item.state }}"  provider="{{ creds }}"
        with_items: "{{ vlan_list }}"

      - name: Saving Configuration
        nxos_config:
          provider: "{{ creds }}"
          lines:
            - 'copy run start'
