---
- name: Deploy vlan
  hosts: leafs
  connection: local
  gather_facts: no

  tasks:
      - name: obtaining login credentials
        include_vars: credentials.yml

      - name: obtaining vlan list
        include_vars: vlan_list.yml

      - name: obtaining server port list
        include_vars: port_list.yml

      - name: configing vlans
        nxos_vlan: vlan_id="{{ item.id }}"  name="{{ item.name }}" state="{{ item.state }}" provider="{{ creds }}"
        with_items: "{{ vlan_list }}"

      - name: configing descriptionserver ports
        nxos_interface: interface="{{ item.port }}" description="{{ item.description }}" provider="{{ creds }}"
        with_items: "{{ port_list }}"

      - name: configing server ports
        nxos_switchport: interface="{{ item.port }}" mode=access access_vlan="{{ item.vlan }}" provider="{{ creds }}"
        with_items: "{{ port_list }}"
