---
- name: Deploy vlan
  hosts: leafs
  connection: local
  gather_facts: no

  tasks:
      - name: obtain login credentials
        include_vars: credentials.yml

      - name: config vlan list of vlans
        nxos_vlan: vlan_id={{ item.id }}  name={{ item.name }} state="{{ item.state }}" provider="{{ creds }}"
        with_items:
          - { id: 20, name: 'WEB-example-2', state: present }
          - { id: 30, name: 'APP-example-2' , state: present }
